/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mob_mobpush_cocos2dx_MobPushReceiver */

#ifndef _Included_com_mob_mobpush_cocos2dx_MobPushReceiver
#define _Included_com_mob_mobpush_cocos2dx_MobPushReceiver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mob_mobpush_cocos2dx_MobPushReceiver
 * Method:    nativeOnCreateCxxObject
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mob_mobpush_cocos2dx_MobPushReceiver_nativeOnCreateCxxObject
  (JNIEnv *, jobject);

/*
 * Class:     com_mob_mobpush_cocos2dx_MobPushReceiver
 * Method:    nativeOnDestoryCxxObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mob_mobpush_cocos2dx_MobPushReceiver_nativeOnDestoryCxxObject
  (JNIEnv *, jobject);

/*
 * Class:     com_mob_mobpush_cocos2dx_MobPushReceiver
 * Method:    nativeOnCustomMessageReceive
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mob_mobpush_cocos2dx_MobPushReceiver_nativeOnCustomMessageReceive
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mob_mobpush_cocos2dx_MobPushReceiver
 * Method:    nativeOnNotifyMessageReceive
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mob_mobpush_cocos2dx_MobPushReceiver_nativeOnNotifyMessageReceive
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mob_mobpush_cocos2dx_MobPushReceiver
 * Method:    nativeOnNotifyMessageOpenedReceive
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mob_mobpush_cocos2dx_MobPushReceiver_nativeOnNotifyMessageOpenedReceive
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mob_mobpush_cocos2dx_MobPushReceiver
 * Method:    nativeOnTagsCallback
 * Signature: ([Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_mob_mobpush_cocos2dx_MobPushReceiver_nativeOnTagsCallback
  (JNIEnv *, jobject, jobjectArray, jint, jint);

/*
 * Class:     com_mob_mobpush_cocos2dx_MobPushReceiver
 * Method:    nativeOnAliasCallback
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_mob_mobpush_cocos2dx_MobPushReceiver_nativeOnAliasCallback
  (JNIEnv *, jobject, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
