/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mob_mobpush_cocos2dx_MobPushCallback */

#ifndef _Included_com_mob_mobpush_cocos2dx_MobPushCallback
#define _Included_com_mob_mobpush_cocos2dx_MobPushCallback
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mob_mobpush_cocos2dx_MobPushCallback
 * Method:    nativeOnCreateCxxObject
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mob_mobpush_cocos2dx_MobPushCallback_nativeOnCreateCxxObject
  (JNIEnv *, jobject);

/*
 * Class:     com_mob_mobpush_cocos2dx_MobPushCallback
 * Method:    nativeOnCallback
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_mob_mobpush_cocos2dx_MobPushCallback_nativeOnCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mob_mobpush_cocos2dx_MobPushCallback
 * Method:    nativeOnDestoryCxxObject
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mob_mobpush_cocos2dx_MobPushCallback_nativeOnDestoryCxxObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
