/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mob_mobpush_cocos2dx_MobPushSReqCallback */

#ifndef _Included_com_mob_mobpush_cocos2dx_MobPushSReqCallback
#define _Included_com_mob_mobpush_cocos2dx_MobPushSReqCallback
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mob_mobpush_cocos2dx_MobPushSReqCallback
 * Method:    nativeOnCreateCxxObject
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mob_mobpush_cocos2dx_MobPushSReqCallback_nativeOnCreateCxxObject
  (JNIEnv *, jobject);

/*
 * Class:     com_mob_mobpush_cocos2dx_MobPushSReqCallback
 * Method:    nativeOnCallback
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_mob_mobpush_cocos2dx_MobPushSReqCallback_nativeOnCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mob_mobpush_cocos2dx_MobPushSReqCallback
 * Method:    nativeOnDestoryCxxObject
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mob_mobpush_cocos2dx_MobPushSReqCallback_nativeOnDestoryCxxObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
