//
// Created by yyfu on 2018/5/16.
//

#ifndef PROJ_ANDROID_STUDIO_C2DXMOBPUSHCUSTOMMESSAGE_H
#define PROJ_ANDROID_STUDIO_C2DXMOBPUSHCUSTOMMESSAGE_H


class C2DXMobPushCustomMessage {
public:
    

};


#endif //PROJ_ANDROID_STUDIO_C2DXMOBPUSHCUSTOMMESSAGE_H
